version: 2.0.0.{build}
image: Visual Studio 2022


environment:
  matrix:
  - PlatformToolset: v143

platform:
    - x64
    - Win32

configuration:
    - RelWithDebInfo

install:
    - cd C:\Tools\vcpkg
    - git pull
    - .\bootstrap-vcpkg.bat
    - cd %APPVEYOR_BUILD_FOLDER%

    - if "%platform%"=="x64" set archi=amd64
    - if "%platform%"=="x64" set platform_input=x64
    - if "%platform%"=="x64" set vcpkg_triplet_arch=x64

    - if "%platform%"=="Win32" set archi=x86
    - if "%platform%"=="Win32" set platform_input=Win32
    - if "%platform%"=="Win32" set vcpkg_triplet_arch=x86

    - call "C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Auxiliary\Build\vcvarsall.bat" %archi%

build_script:
    - echo %vcpkg_triplet_arch%
    - cmake . -B"build" -G "Visual Studio 17 2022" -A %platform_input% -DCMAKE_TOOLCHAIN_FILE=C:\Tools\vcpkg\scripts\buildsystems\vcpkg.cmake -DVCPKG_TARGET_TRIPLET=%vcpkg_triplet_arch%-windows-static -DVCPKG_OVERLAY_TRIPLETS=./vcpkg/triplets
    - cmake --build "build" --config RelWithDebInfo

after_build:
    - cd "%APPVEYOR_BUILD_FOLDER%"
    - ps: >-

        if ($env:PLATFORM_INPUT -eq "x64") {
            Push-AppveyorArtifact "bin\$env:CONFIGURATION\NppBplistPlugin.dll" -FileName NppBplistPlugin.dll
        }

        if ($env:PLATFORM_INPUT -eq "Win32" ) {
            Push-AppveyorArtifact "bin\$env:CONFIGURATION\NppBplistPlugin.dll" -FileName NppBplistPlugin.dll
        }

        if ($($env:APPVEYOR_REPO_TAG) -eq "true" -and $env:PLATFORMTOOLSET -eq "%PlatformToolset%") {
            if($env:PLATFORM_INPUT -eq "x64"){
                $ZipFileName = "NppBplistPlugin_$($env:APPVEYOR_REPO_TAG_NAME)_x64.zip"
                7z a $ZipFileName bin\$env:CONFIGURATION\NppBplistPlugin.dll
            }
            if($env:PLATFORM_INPUT -eq "Win32"){
                $ZipFileName = "NppBplistPlugin_$($env:APPVEYOR_REPO_TAG_NAME)_x86.zip"
                7z a $ZipFileName bin\$env:CONFIGURATION\NppBplistPlugin.dll
            }
        }

artifacts:
  - path: NppBplistPlugin_*.zip
    name: releases

deploy:
    provider: GitHub
    auth_token:
        secure: !!TODO, see https://www.appveyor.com/docs/deployment/github/#provider-settings!!
    artifact: releases
    draft: false
    prerelease: false
    force_update: true
    on:
        appveyor_repo_tag: true
        PlatformToolset: v143
        configuration: Release
